package com.sample
import java.util.ArrayList;
import java.util.ArrayList
import javax.swing.JOptionPane;

declare Question
	question : String
	answers : ArrayList
	answer : String
end

declare Recommendation
	recommendation : String
end

function void askQuestion(Question q){
	String newAnswer = GUI.askQuestionGUI(q.getAnswers(),q.getQuestion());
	q.setAnswer(newAnswer);
}

function Recommendation showingRecommendation(String recommendation){
	GUI.showingRecommendationGUI(recommendation);
	return new Recommendation(recommendation);
	
}